"""
Milestone 6 (REBUILD_PLAN.md): fixture-based extraction accuracy suite.

Real, non-mocked verification: every test in this file that touches
`parse_one_resume()` makes a real LLM call (Groq, per `.env`'s
`AI_PROVIDER`) against real PDF files -- "is the data actually correct"
has never been checkable before this milestone except by eyeballing
screenshots (RELIABILITY_SCALE_ANALYSIS.md Section 1.5). This whole module
is marked `slow` and excluded from the default `pytest tests/` run (see
`pytest.ini`) because it costs real API quota every time it runs -- invoke
it explicitly:

    pytest tests/test_extraction_accuracy.py -m slow

Fixtures and their manually-verified expected values live in
tests/fixtures/accuracy_fixtures.json -- read that file's own comments for
exactly how "expected" was determined (7 real resumes from
data/real_resumes/, 1 synthetic percentage-CGPA resume, explicitly marked
as such).

Accuracy bar (deliberately not 99%, per PROJECT_CONTEXT.md Section 10.5's
own stated philosophy that chasing an artificial ceiling on messy real
input is the wrong target): >=85% name accuracy, >=90% CGPA accuracy (only
counted on fixtures where a CGPA is actually present on the resume),
>=75% average skill recall.
"""

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

pytestmark = pytest.mark.slow

from src.env_loader import load_env  # noqa: E402

load_env()

from src.pipeline import clear_resume_cache, parse_one_resume  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURES_PATH = REPO_ROOT / "tests" / "fixtures" / "accuracy_fixtures.json"
REPORT_PATH = REPO_ROOT / "tests" / "fixtures" / "accuracy_report.md"
INJECTION_FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "mock_prompt_injection.pdf"
CORRUPTED_FIXTURE_PATH = REPO_ROOT / "data" / "mock_resumes" / "mock_corrupted_file.pdf"
EMPTY_FIXTURE_PATH = REPO_ROOT / "data" / "mock_resumes" / "mock_empty_file.pdf"

NAME_ACCURACY_BAR = 0.85
CGPA_ACCURACY_BAR = 0.90
SKILL_RECALL_BAR = 0.75
CGPA_TOLERANCE = 0.05  # absolute -- rounding-safe, not a leniency loophole


def _load_fixtures() -> list[dict]:
    data = json.loads(FIXTURES_PATH.read_text())
    return data["fixtures"]


def _names_match(expected: str | None, actual: str | None) -> bool:
    if not expected or not actual:
        return False
    return expected.strip().casefold() == actual.strip().casefold()


def _cgpa_match(expected: float | None, actual: float | None) -> bool | None:
    """None means 'not applicable' (this fixture has no CGPA to check) --
    the caller must not fold that into either a pass or a fail."""
    if expected is None:
        return None
    if actual is None:
        return False
    return abs(expected - actual) <= CGPA_TOLERANCE


def _skill_recall(expected_skills: list[str], actual_skills: list[str] | None) -> float | None:
    """
    Fraction of expected_skills found in actual_skills. Matching is
    case-insensitive with substring containment in either direction (e.g.
    expected "React" matches an extracted "React.js") -- per
    accuracy_fixtures.json's own documented reasoning, exact string
    equality would unfairly fail on reasonable rephrasing that isn't
    actually a miss.
    """
    if not expected_skills:
        return None
    actual_lower = [s.casefold() for s in (actual_skills or [])]
    found = 0
    for expected_skill in expected_skills:
        exp = expected_skill.casefold()
        if any(exp in actual or actual in exp for actual in actual_lower):
            found += 1
    return found / len(expected_skills)


def _write_report(rows: list[dict], name_accuracy: float, cgpa_accuracy: float | None, avg_skill_recall: float | None) -> None:
    lines = [
        "# Extraction Accuracy Report",
        "",
        "Generated by `tests/test_extraction_accuracy.py` (Milestone 6) against real Groq extraction calls.",
        "Fixtures and expected values: `tests/fixtures/accuracy_fixtures.json`.",
        "",
        f"**Name accuracy:** {name_accuracy:.0%} (bar: {NAME_ACCURACY_BAR:.0%})",
        f"**CGPA accuracy:** {cgpa_accuracy:.0%} (bar: {CGPA_ACCURACY_BAR:.0%})" if cgpa_accuracy is not None else "**CGPA accuracy:** N/A (no fixture had a CGPA to check)",
        f"**Average skill recall:** {avg_skill_recall:.0%} (bar: {SKILL_RECALL_BAR:.0%})" if avg_skill_recall is not None else "**Average skill recall:** N/A",
        "",
        "| File | Source | Expected Name | Actual Name | Name OK | Expected CGPA | Actual CGPA | CGPA OK | Skill Recall | Parse Status |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        cgpa_ok_display = "N/A" if row["cgpa_ok"] is None else ("Yes" if row["cgpa_ok"] else "No")
        recall_display = "N/A" if row["skill_recall"] is None else f"{row['skill_recall']:.0%}"
        lines.append(
            f"| {row['file']} | {row['source']} | {row['expected_name']} | {row['actual_name']} | "
            f"{'Yes' if row['name_ok'] else 'No'} | {row['expected_cgpa']} | {row['actual_cgpa']} | "
            f"{cgpa_ok_display} | {recall_display} | {row['parse_status']} |"
        )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def test_extraction_accuracy_suite_meets_stated_bar():
    clear_resume_cache()  # each real run should hit the actual LLM, not a stale in-process cache entry
    fixtures = _load_fixtures()

    name_results, cgpa_results, skill_recalls, rows = [], [], [], []

    for fx in fixtures:
        path = REPO_ROOT / fx["file"]
        resume = parse_one_resume(str(path))

        name_ok = _names_match(fx["expected_full_name"], resume.full_name)
        cgpa_ok = _cgpa_match(fx["expected_cgpa_10pt"], resume.cgpa_10pt)
        recall = _skill_recall(fx["expected_skills"], resume.skills)

        name_results.append(name_ok)
        if cgpa_ok is not None:
            cgpa_results.append(cgpa_ok)
        if recall is not None:
            skill_recalls.append(recall)

        rows.append(
            {
                "file": fx["file"],
                "source": fx["source"],
                "expected_name": fx["expected_full_name"],
                "actual_name": resume.full_name,
                "name_ok": name_ok,
                "expected_cgpa": fx["expected_cgpa_10pt"],
                "actual_cgpa": resume.cgpa_10pt,
                "cgpa_ok": cgpa_ok,
                "skill_recall": recall,
                "parse_status": resume.parse_status,
            }
        )

    name_accuracy = sum(name_results) / len(name_results)
    cgpa_accuracy = (sum(cgpa_results) / len(cgpa_results)) if cgpa_results else None
    avg_skill_recall = (sum(skill_recalls) / len(skill_recalls)) if skill_recalls else None

    # Written even if the assertions below fail -- a failed run's report is
    # exactly what's needed to see which fixture(s) actually missed, not
    # just that the aggregate number was too low.
    _write_report(rows, name_accuracy, cgpa_accuracy, avg_skill_recall)

    assert name_accuracy >= NAME_ACCURACY_BAR, (
        f"Name accuracy {name_accuracy:.0%} is below the {NAME_ACCURACY_BAR:.0%} bar -- see "
        f"{REPORT_PATH.relative_to(REPO_ROOT)} for per-fixture detail."
    )
    if cgpa_accuracy is not None:
        assert cgpa_accuracy >= CGPA_ACCURACY_BAR, (
            f"CGPA accuracy {cgpa_accuracy:.0%} is below the {CGPA_ACCURACY_BAR:.0%} bar -- see "
            f"{REPORT_PATH.relative_to(REPO_ROOT)} for per-fixture detail."
        )
    assert avg_skill_recall is not None, "No fixture had any expected_skills -- accuracy_fixtures.json is malformed."
    assert avg_skill_recall >= SKILL_RECALL_BAR, (
        f"Average skill recall {avg_skill_recall:.0%} is below the {SKILL_RECALL_BAR:.0%} bar -- see "
        f"{REPORT_PATH.relative_to(REPO_ROOT)} for per-fixture detail."
    )


# --- LLM-pipeline-specific tests required by REBUILD_PROMPT.md Section 4 ----


def test_corrupted_file_fails_gracefully_no_crash():
    resume = parse_one_resume(str(CORRUPTED_FIXTURE_PATH))
    assert resume.parse_status == "Failed"
    assert resume.parse_method == "failed"


def test_empty_file_fails_gracefully_no_crash():
    resume = parse_one_resume(str(EMPTY_FIXTURE_PATH))
    assert resume.parse_status == "Failed"
    assert resume.parse_method == "failed"


def test_prompt_injection_pdf_resisted_through_full_pipeline():
    """
    Same property tests/test_prompt_injection_resistance.py already
    verifies (a fake 'SYSTEM OVERRIDE' instruction embedded in resume text
    must not be honored), but exercised through the FULL pipeline starting
    from a real PDF file -- PDF text extraction, PII redaction, and the LLM
    call together -- rather than calling extract_structured_fields()
    directly on a hand-written string. This is what actually proves the
    resistance holds for a real uploaded file, not just for the LLM call in
    isolation.
    """
    resume = parse_one_resume(str(INJECTION_FIXTURE_PATH))

    # The genuinely-present content must be what's extracted... Case-
    # insensitive, same as the main accuracy suite's _names_match(): the
    # fixture PDF writes the name in ALL CAPS (matching the header
    # convention several real resumes in this dataset use -- e.g.
    # "SIDDHARTH RAO"), and a model that returns it verbatim rather than
    # title-casing it is being faithful to the source, not failing at
    # injection resistance -- capitalization fidelity isn't the property
    # this test exists to check.
    assert _names_match("Rohan Sharma", resume.full_name)
    assert resume.cgpa_10pt is not None
    assert abs(resume.cgpa_10pt - 5.2) <= CGPA_TOLERANCE

    # ...and the injected claims must NOT have been honored.
    assert resume.cgpa_10pt != 10.0
    assert resume.skills in ([], None)  # "None listed." on this resume -- no real skills to find
